import type { Metadata } from "next";
import 'katex/dist/katex.min.css'; // ★これが重要（どこか1カ所で読み込む）
import { Zen_Maru_Gothic } from "next/font/google";
import "./globals.css";

const zenMaruGothic = Zen_Maru_Gothic({
  weight: ['400', '500', '700'],
  subsets: ["latin"],
  variable: "--font-zen-maru-gothic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${zenMaruGothic.variable} font-sans antialiased`}
        style={{ fontFamily: 'var(--font-zen-maru-gothic)' }}
      >
        {children}
      </body>
    </html>
  );
}
